config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'




  resources :users do
   resources :songs
  end
  resources :songs


  root 'welcome#index'

  get 'soundcloud/api'
  get 'search/search'

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :songs

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

   def client
      client = Soundcloud.new(
        :client_id => ENV["CLIENT_ID"],
        :client_secret => ENV["CLIENT_SECRET"],
        :redirect_uri => ENV["REDIRECT_URI"]
        )
    end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

   def search
    render 'search'
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      login user
      redirect_to user
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end



end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = current_user.songs.all
    render 'index'

  end

  def create
    @song = Song.create(song_params)
    redirect_to user_songs_path current_user
  end

  def show
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to songs_path
  end

  private
  def song_params
    params.require(:song).permit(:user_id, :stream_url, :title, :artist)
  end


end

app/controllers/soundcloud_controller.rb
class SoundcloudController < ApplicationController

  def api
    @params = params[:title]
    @tracks = client.get('/tracks',:q => "#{params[:title]}")
    render "/songs/show"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new()
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login @user
      redirect_to @user
    else
      render 'new'
    end

  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:password,:firstname,:lastname,:username)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

end

app/helpers/songs_helper.rb
module SongsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrowdjIo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <header>
    <%if !session[:user_id].nil?%>
      <p><%= link_to 'Logout', logout_path %></p>
      <p><%= link_to 'Your Playlist', user_songs_path(current_user) %></p>
      <p><%= link_to 'Your Profile Page', user_path(current_user) %></p>
    <%else%>
      <p><%= link_to 'Login', login_path %></p>
    <%end%>
  </header>
<body>
<%= yield %>

</body>
</html>

app/views/search/search.html.erb
<h1>Welcome to Crowdj.io</h1>

  <%if !session[:user_id].nil?%>
    <h2>Search a SoundCloud song</h2>

    <form action="/soundcloud/api" method="get" >
      <input name="title" type="text">
      <input type="submit">
    </form>

  <%else%>
    <h4>Please log in if you would like to listen to music</h4>
    <%= link_to 'Login', {:controller => 'sessions', :action => 'new'} %>
  <%end%>

app/views/songs/index.html.erb
<h1>Your Songs</h1>

  <%@songs.each do |song|%>
    <h3><%= song.title %></h3>
    <audio controls>
      <source src=<%=song.stream_url+'?client_id='+ENV["CLIENT_ID"] %> type="audio/ogg">
    </audio>
    <%= button_to 'Delete', user_song_path(song.user_id,song.id), method: :delete %>
  <%end%>

app/views/songs/new.html.erb
NEW

app/views/songs/show.html.erb
<ul class="small-clock-grid-3">

  <h1>Soundcloud found for <%=@params.capitalize%></h1>

  <%@tracks.each do |track|%>
    <li>
      <div class="row">
      <div class="small-8 columns">
        <img src="<%=track.artwork_url%>"></img>
        <%=track.title%>
        <audio controls>
            <source src=<%=track.stream_url+'?client_id='+ENV["CLIENT_ID"] %> type="audio/ogg">
        </audio>
          <%=form_for :song, url: songs_path do |f| %>
            <%= f.hidden_field :stream_url,:value => track.stream_url %>
            <%= f.hidden_field :user_id,:value => current_user.id %>
            <%= f.hidden_field :title,:value => track.title %>
            <%= f.hidden_field :artist,:value => track.artist %>
          <%=f.submit%>
          <%end%>
      </div>
    </div>
  </li>
  <%end%>
</ul>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

  <%= form_for @user do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :firstname %>

    <%= f.label :last_name %>
    <%= f.text_field :lastname %>

    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit %>
  <%end%>

app/views/users/show.html.erb
<h1>Hello, <%=@user.username.capitalize%></h1>

  <% if !session[:user_id].nil? %>
    <h6><%= link_to "Start Listening!", {:controller => 'search', :action =>'search'} %></h6>
  <%end%>

app/views/welcome/index.html.erb
<h1>Welcome to Crowdj.io</h1>


<h3><%= link_to "Login", login_path %></h3>
<h3><%= link_to "Signup", signup_path %></h3>